<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.1 setup script
 * Date: Fri, 15 Nov 2019 08:13:54 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: srv1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'srv2';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'jikken2019';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'tr.>6~du)1b9C&"pi5F}D7r6A4@")tI>';
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
